export const authConstants = {
    
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',

    LOGOUT_REQUEST:'LOGOUT_REQUEST',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    LOGOUT_FAILURE:'LOGOUT_FAILURE',
}

export const userConstants = {
    USER_REGISTER_REQUEST:'USER_REGISTER_REQUEST',
    USER_REGISTER_SUCCESS:'USER_REGISTER_SUCCESS',
    USER_REGISTER_FAILURE:'USER_REGISTER_FAILURE',

}


export const categoryContstants = {
    GET_ALL_CATEGORY_REQUEST:'GET_ALL_CATEGORY_REQUEST',
    GET_ALL_CATEGORY_SUCCESS:'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILURE:'GET_ALL_CATEGORY_FAILURE',

    CATEGORY_CREATE_REQUEST:'CATEGORY_CREATE_REQUEST',
    CATEGORY_CREATE_SUCCESS:'CATEGORY_CREATE_SUCCESS',
    CATEGORY_CREATE_FAILURE:'CATEGORY_CREATE_FAILURE',

}